version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: terraform
    directories:
      - /bootstrap
      - /modules/*
      - /projects/*
    schedule:
      interval: weekly
    groups:
      terraform-providers:
        patterns: ["*"]

  - package-ecosystem: pip
    directories:
      - /projects/02-serverless-order-pipeline
      - /projects/04-finops-automation
    schedule:
      interval: weekly
    groups:
      python-dev:
        patterns: ["*"]
